<?php
session_start();
// Include the navigation bar. Ensure 'stdnav.php' correctly handles session and
// outputs the HTML for the navigation.
include 'admin.php';

// Define the base directory for data storage and uploads
$talentDataDir = 'talent_data/';
$jsonFilePath = $talentDataDir . 'talents.json';
$upload_dir = $talentDataDir . 'uploads/'; // Directory where uploaded media files are stored

// Function to read all talents from the JSON file
function readTalents($filePath) {
    if (!file_exists($filePath) || filesize($filePath) == 0) {
        return []; // Return empty array if file doesn't exist or is empty
    }
    $jsonContent = file_get_contents($filePath);
    $talents = json_decode($jsonContent, true); // Decode as associative array
    return is_array($talents) ? $talents : []; // Ensure it's an array
}

// Read all talents
$allTalents = readTalents($jsonFilePath);

// Sort talents by timestamp in descending order (newest first)
// The 'timestamp' key generated by stdtalentpost.php is in 'Y-m-d H:i:s' format,
// so we need to convert them to Unix timestamps for proper comparison.
usort($allTalents, function($a, $b) {
    $timeA = strtotime($a['timestamp'] ?? '1970-01-01 00:00:00'); // Fallback for missing timestamp
    $timeB = strtotime($b['timestamp'] ?? '1970-01-01 00:00:00'); // Fallback for missing timestamp
    return $timeB <=> $timeA; // $b first for descending order
});

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Talent Showcase - View All Posts</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        /* --- Variables (from Talent Showcase Home page) --- */
        :root {
            --primary-light: #e3f2fd; /* Light Blue */
            --primary-medium: #bbdefb; /* Medium Blue */
            --primary-dark: #90caf9; /* Darker Blue */
            --accent-light: #42a5f5; /* Vibrant Blue */
            --accent-medium: #2196f3; /* Strong Blue */
            --accent-dark: #1976d2; /* Deep Blue */
            --text-dark: #1a237e; /* Dark Indigo */
            --text-green: #283593; /* Medium Indigo for contrast */
            --gradient-1: linear-gradient(135deg, var(--primary-light) 0%, var(--primary-medium) 50%, var(--primary-dark) 100%);
            --gradient-accent: linear-gradient(90deg, var(--accent-light), var(--accent-medium));
            --shadow-light: 0 4px 15px rgba(0, 0, 0, 0.1);
            --shadow-medium: 0 8px 30px rgba(33, 150, 243, 0.15); /* Adjusted shadow color */
            --shadow-heavy: 0 15px 45px rgba(0, 0, 0, 0.25);
        }

        /* --- Base Styles --- */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--gradient-1);
            min-height: 100vh;
            color: var(--text-dark);
            position: relative;
            overflow-x: hidden;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        /* Animated background elements */
        body::before, body::after {
            content: '';
            position: fixed;
            border-radius: 50%;
            background: rgba(33, 150, 243, 0.08); /* Adjusted color */
            z-index: -1;
            filter: blur(10px);
        }

        body::before {
            top: -10%;
            left: -10%;
            width: 50vw;
            height: 50vw;
            animation: floatShape 25s ease-in-out infinite;
        }

        body::after {
            bottom: -10%;
            right: -10%;
            width: 60vw;
            height: 60vw;
            animation: floatShape 20s ease-in-out infinite reverse;
        }

        @keyframes floatShape {
            0%, 100% { transform: translate(0, 0) scale(1); opacity: 0.7; }
            50% { transform: translate(20px, 30px) scale(1.05); opacity: 0.4; }
        }

        /* --- Navbar Styles --- */
        .navbar {
            background: rgba(255, 255, 255, 0.2);
            backdrop-filter: blur(25px);
            border-bottom: 1px solid rgba(33, 150, 243, 0.3); /* Adjusted color */
            padding: 18px 40px;
            position: sticky;
            top: 0;
            z-index: 100;
            box-shadow: var(--shadow-medium);
            width: 100%;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .navbar-brand {
            font-size: 1.8em;
            font-weight: 800;
            color: var(--accent-dark);
            text-decoration: none;
            display: flex;
            align-items: center;
            gap: 10px;
            text-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
        }

        .navbar-brand i {
            color: var(--accent-medium);
            font-size: 1.1em;
        }

        .navbar-links {
            display: flex;
            gap: 22px;
        }

        .navbar-links a {
            text-decoration: none;
            color: var(--accent-medium);
            font-weight: 600;
            font-size: 1.05em;
            position: relative;
            transition: all 0.3s ease;
            text-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
            display: flex; /* Added for icon alignment */
            align-items: center; /* Added for icon alignment */
            gap: 6px; /* Space between icon and text */
        }

        .navbar-links a::after {
            content: '';
            position: absolute;
            bottom: -7px;
            left: 50%;
            width: 0;
            height: 3px;
            background: var(--gradient-accent);
            transition: all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94);
            transform: translateX(-50%);
            border-radius: 2px;
        }

        .navbar-links a:hover {
            color: var(--accent-dark);
            transform: translateY(-3px);
        }

        .navbar-links a:hover::after {
            width: 100%;
        }

        /* Active link styling (applied by dynamically adding 'active' class) */
        .navbar-links a.active {
            color: var(--accent-dark);
            font-weight: 700;
        }
        .navbar-links a.active::after {
            width: 100%;
        }


        /* --- Main Content Styles --- */
        .main-container {
            max-width: 1200px;
            width: 90%; /* Adjusted for better responsiveness */
            margin: 50px auto; /* Center the container and add vertical spacing */
            text-align: center; /* Center the overall content */
            flex-grow: 1;
            padding: 0 20px; /* Add some padding to the sides */
        }

        h1 {
            font-size: 4.2rem;
            font-weight: 800;
            margin-bottom: 25px;
            text-shadow: 0 5px 12px rgba(0, 0, 0, 0.12);
            background: linear-gradient(135deg, var(--accent-dark), var(--accent-medium), var(--accent-light));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 15px;
            animation: slideDown 1s ease-out forwards;
        }

        h1 i {
            font-size: 0.9em;
            color: var(--accent-medium);
        }
        
        .page-subtitle {
            font-size: 1.5rem;
            color: var(--text-green);
            margin-bottom: 50px;
            max-width: 850px;
            margin-left: auto;
            margin-right: auto;
            line-height: 1.7;
            animation: fadeIn 1.2s ease-out 0.4s both;
        }

        @keyframes slideDown {
            from { opacity: 0; transform: translateY(-60px); }
            to { opacity: 1; transform: translateY(0); }
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(30px); }
            to { opacity: 1; transform: translateY(0); }
        }

        /* --- Post Card Styles --- */
        .posts-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); /* Adjusted minmax for better spacing */
            gap: 30px;
            margin-top: 40px;
            text-align: left; /* Align text within cards */
            justify-content: center; /* Center cards in the grid */
        }

        .post-card {
            background: #fff;
            border: 1px solid var(--primary-medium);
            border-radius: 12px;
            padding: 25px;
            box-shadow: var(--shadow-medium);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            display: flex;
            flex-direction: column;
            justify-content: space-between; /* Distributes space between items */
            height: auto; /* Allow height to adjust to content */
        }

        .post-card:hover {
            transform: translateY(-8px);
            box-shadow: var(--shadow-heavy);
        }

        .post-card h3 {
            font-size: 1.8em;
            color: var(--accent-dark);
            margin-bottom: 10px;
            word-wrap: break-word; /* Prevent long titles from overflowing */
        }

        .post-card p {
            font-size: 1.1em;
            color: var(--text-dark);
            margin-bottom: 15px;
            line-height: 1.5;
            word-wrap: break-word;
        }

        .post-card .uploaded-content {
            margin-top: 15px;
            margin-bottom: 15px;
            text-align: center; /* Center media */
        }

        .post-card .uploaded-content img,
        .post-card .uploaded-content video,
        .post-card .uploaded-content audio { /* Added audio for consistency */
            max-width: 100%; /* Ensure media fits within card */
            height: auto; /* Maintain aspect ratio */
            border-radius: 8px;
            box-shadow: var(--shadow-light);
            display: block; /* Remove extra space below images/videos */
            margin: 0 auto; /* Center block elements */
        }
        
        /* Specific height for images/videos in desktop view, but adaptable */
        @media (min-width: 769px) {
             .post-card .uploaded-content img,
             .post-card .uploaded-content video {
                height: 250px; /* Fixed height for consistency on larger screens */
                object-fit: cover; /* Cover the area, cropping if necessary */
            }
        }
        
        .post-card .uploaded-content p {
            font-size: 0.9em;
            color: #666;
            margin-top: 10px;
        }

        .post-card .uploaded-content a {
            color: var(--accent-medium);
            text-decoration: none;
            font-weight: 600;
            transition: color 0.3s ease;
        }

        .post-card .uploaded-content a:hover {
            color: var(--accent-dark);
            text-decoration: underline;
        }

        .post-card .external-link {
            font-size: 0.95em;
            margin-top: 10px;
            word-wrap: break-word;
        }

        .post-card .external-link a {
            color: var(--accent-medium);
            text-decoration: none;
            font-weight: 600;
            display: flex;
            align-items: center;
            gap: 5px;
        }

        .post-card .external-link a:hover {
            color: var(--accent-dark);
            text-decoration: underline;
        }

        .post-card .post-meta {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: auto; /* Push to the bottom */
            padding-top: 15px;
            border-top: 1px dashed var(--primary-medium);
            font-size: 0.9em;
            color: #666;
        }

        .post-card .post-author {
            font-weight: 600;
            color: var(--text-dark);
        }

        .post-card .post-date {
            font-style: italic;
            color: #888;
        }

        /* --- Message for no posts --- */
        .no-posts-message {
            font-size: 1.4em;
            color: var(--text-green);
            padding: 50px;
            border: 2px dashed var(--primary-dark);
            border-radius: 10px;
            max-width: 600px;
            margin: 50px auto;
            background: rgba(255, 255, 255, 0.5);
            box-shadow: var(--shadow-light);
            text-align: center;
        }

        /* --- Footer (Optional but good practice) --- */
        .footer {
            margin-top: 60px; /* Increased margin for better separation */
            padding: 30px 20px;
            text-align: center;
            color: var(--text-dark);
            font-size: 0.9em;
            background: rgba(255, 255, 255, 0.1);
            width: 100%;
            border-top: 1px solid rgba(33, 150, 243, 0.1); /* Adjusted color */
        }

        /* --- Responsive Design --- */
        @media (max-width: 992px) {
            .navbar {
                padding: 18px 20px;
            }
            .navbar-brand {
                font-size: 1.6em;
            }
            .navbar-links a {
                font-size: 1em;
            }
            h1 {
                font-size: 3.5rem;
            }
            .page-subtitle {
                font-size: 1.3rem;
            }
            .post-card h3 {
                font-size: 1.6em;
            }
            .post-card p {
                font-size: 1em;
            }
        }

        @media (max-width: 768px) {
            .navbar {
                flex-direction: column;
                align-items: flex-start;
                padding: 15px 20px;
            }
            .navbar-brand {
                margin-bottom: 15px;
            }
            .navbar-links {
                flex-direction: column;
                width: 100%;
                gap: 10px;
            }
            .navbar-links a {
                padding: 8px 0;
                text-align: left;
                width: 100%;
                border-bottom: 1px solid rgba(33, 150, 243, 0.1);
            }
            .navbar-links a:last-child {
                border-bottom: none;
            }
            .navbar-links a::after {
                left: 0;
                transform: translateX(0);
                width: 0;
            }
            .navbar-links a:hover::after {
                width: 30%;
            }

            h1 {
                font-size: 2.8rem;
                flex-direction: column;
                gap: 5px;
            }
            h1 i {
                font-size: 1em;
            }
            .page-subtitle {
                font-size: 1.1rem;
                padding: 0 15px;
                margin-bottom: 40px;
            }
            .posts-grid {
                grid-template-columns: 1fr;
                padding: 0 15px;
                gap: 20px;
            }
            .post-card {
                padding: 20px;
            }
            .no-posts-message {
                font-size: 1.2em;
                padding: 30px;
            }
        }

        @media (max-width: 480px) {
            .navbar-brand {
                font-size: 1.4em;
            }
            .navbar-links a {
                font-size: 0.9em;
            }
            h1 {
                font-size: 2.2rem;
            }
            .page-subtitle {
                font-size: 1rem;
            }
            .main-container {
                padding: 40px 10px;
            }
            .post-card h3 {
                font-size: 1.4em;
            }
            .post-card p {
                font-size: 0.9em;
            }
        }

        .srr{
            margin-left:270px;
        }
    </style>
</head>
<body class="srr">

    <div class="main-container">
        <h1>
            <i class="fas fa-magnifying-glass"></i> All Student Posts
        </h1>
        <p class="page-subtitle">
            Explore the incredible talents shared by students across various fields! From art and music to coding and innovation, discover what makes our student community shine.
        </p>

        <section id="student-posts-list" class="posts-grid">
            <?php
            // Check if the talent data directory exists and is readable
            if (!is_dir($talentDataDir) || !is_readable($talentDataDir)) {
                echo '<p class="no-posts-message"><strong>Error:</strong> The talent data directory ("' . htmlspecialchars($talentDataDir) . '") does not exist or is not readable. Please ensure it\'s created and has proper permissions.</p>';
            } elseif (!file_exists($jsonFilePath) || filesize($jsonFilePath) == 0) {
                echo '<p class="no-posts-message">No talent posts yet. Be the first to share your amazing work!</p>';
            } elseif (!is_dir($upload_dir) || !is_readable($upload_dir)) {
                echo '<p class="no-posts-message"><strong>Error:</strong> The uploads directory ("' . htmlspecialchars($upload_dir) . '") does not exist or is not readable. Please ensure it\'s created and has proper permissions.</p>';
            } else {
                // If there are no talents after reading the file (e.g., empty array from JSON)
                if (empty($allTalents)) {
                    echo '<p class="no-posts-message">No talent posts yet. Be the first to share your amazing work!</p>';
                } else {
                    // Display each post in a card format
                    foreach ($allTalents as $post) {
                        // Ensure all expected keys exist to prevent warnings
                        $id = htmlspecialchars($post['id'] ?? uniqid('unknown_')); // Fallback ID
                        $rollNumber = htmlspecialchars($post['roll_number'] ?? 'N/A');
                        $name = htmlspecialchars($post['name'] ?? 'Unknown Talent');
                        $description = nl2br(htmlspecialchars($post['description'] ?? 'No description provided.'));
                        $mediaPath = htmlspecialchars($post['media_path'] ?? ''); // This is the full path including directory
                        $externalLink = htmlspecialchars($post['external_link'] ?? '');
                        $timestamp = htmlspecialchars($post['timestamp'] ?? date('Y-m-d H:i:s')); // Fallback timestamp
                        
                        echo '<div class="post-card">';
                        echo '<h3>' . $name . '</h3>';
                        echo '<p>' . $description . '</p>';
                        
                        // Handle uploaded media (image, video, audio)
                        if (!empty($mediaPath)) {
                            // Check if the file actually exists
                            if (file_exists($mediaPath)) {
                                $fileExtension = strtolower(pathinfo($mediaPath, PATHINFO_EXTENSION));

                                echo '<div class="uploaded-content">';
                                if (in_array($fileExtension, ['jpg', 'jpeg', 'png', 'gif', 'webp'])) {
                                    echo '<img src="' . $mediaPath . '" alt="Uploaded Image for ' . $name . '">';
                                } elseif (in_array($fileExtension, ['mp4', 'webm', 'ogg'])) {
                                    echo '<video controls src="' . $mediaPath . '" alt="Uploaded Video for ' . $name . '"></video>';
                                } elseif (in_array($fileExtension, ['mp3', 'wav', 'ogg'])) {
                                    echo '<audio controls src="' . $mediaPath . '"></audio>';
                                } else {
                                    // Fallback for unexpected file types
                                    echo '<p>Download: <a href="' . $mediaPath . '" download="' . basename($mediaPath) . '"><i class="fas fa-download"></i> ' . basename($mediaPath) . '</a></p>';
                                }
                                echo '</div>'; // End uploaded-content
                            } else {
                                // Inform if the linked file is missing
                                echo '<div class="uploaded-content"><p style="color: red;"><em>Uploaded media not found: ' . basename($mediaPath) . '</em></p></div>';
                            }
                        }

                        // Display external link if available
                        if (!empty($externalLink)) {
                            // Basic URL validation
                            if (filter_var($externalLink, FILTER_VALIDATE_URL)) {
                                echo '<p class="external-link">External Link: <a href="' . $externalLink . '" target="_blank" rel="noopener noreferrer"><i class="fas fa-external-link-alt"></i> ' . $externalLink . '</a></p>';
                            } else {
                                echo '<p class="external-link" style="color: red;"><em>Invalid external link: ' . $externalLink . '</em></p>';
                            }
                        }
                        
                        // Display post metadata (author and date)
                        echo '<div class="post-meta">';
                        echo '<span class="post-author">By: <strong>' . $rollNumber . '</strong></span>';
                        // Format the timestamp for display
                        echo '<span class="post-date"><i class="far fa-calendar-alt"></i> ' . date('M d, Y H:i', strtotime($timestamp)) . '</span>';
                        echo '</div>'; // End post-meta
                        echo '</div>'; // End post-card
                    }
                }
            }
            ?>
        </section>
    </div>

    <footer class="footer">
        <p>&copy; 2025 Student Talent Showcase. All rights reserved.</p>
    </footer>

    <script>
        // Simple client-side script to apply 'active' class based on current URL
        document.addEventListener('DOMContentLoaded', () => {
            const currentPath = window.location.pathname.split('/').pop();
            const navLinks = document.querySelectorAll('.navbar-links a');
            navLinks.forEach(link => {
                const linkPath = link.getAttribute('href').split('/').pop();
                if (linkPath === currentPath) {
                    link.classList.add('active');
                } else {
                    link.classList.remove('active'); // Ensure other links are not active
                }
            });
        });
    </script>
</body>
</html>